// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkrqxttzwuvemjfhlqao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrcnF4dHR6d3V2ZW1qZmhscWFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NDEwNzQsImV4cCI6MjA1NTAxNzA3NH0.JSN5TS2h2tdcK1hW84bqm8zoytYrlmbBgS2yp9CeiNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);